# Generated by Django 2.0.1 on 2018-02-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def create_continent(app,schema_editor):
        Continent = app.get_model("continents","Continent")
        Continent.objects.create (name='europa',translate='europe',color='#AE4')
        Continent.objects.create(name='asia', translate='asia',color='#F33')
        Continent.objects.create(name='america',translate='america',color='#D22')
        Continent.objects.create(name='africa',translate='africa',color='#34D')
        Continent.objects.create(name='antartica',translate='antarctica',color='#385')
        Continent.objects.create(name='australia',translate='australia',color='#DEA')

    dependencies = [
        ('continents', '0001_initial'),
        ('countries', '0002_auto_20180204_0826'),
    ]

    operations = [
    migrations.RunPython(create_continent),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='continents.Continent'),
            preserve_default=False,
        ),
    ]
