# Generated by Django 2.0.1 on 2018-02-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0003_country_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('father', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
                ('nacionality', models.ManyToManyField(to='countries.Country')),
            ],
        ),
    ]
